version = 0.1
[onica1]
[onica1.deploy]
[onica1.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iu46bb28fdk1"
s3_prefix = "sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
